package com.trovaApp.enums;

public enum Genre {
    ROCK_ARGENTINO,
    TANGO,
    JAZZ,
    MUSICA_POPULAR_ARGENTINA,
    MUSICA_POPULAR_BRASILENA,
    HUMOR_MUSICAL,
    CHANSON_FRANCESA,
    TEATRO_MUSICAL,
    FOLCLORE,
    CONTEMPORÁNEA,
    CLÄSICA
}
